name: Docker image

on:
  pull_request:

env:
  IMAGE_NAME: proxmox-docker

jobs:
  build:
    runs-on: docker_runner
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=${{ secrets.BUILDKIT_IMAGE }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ secrets.BUILD_TAG_TEST }}

  test:
    runs-on: docker_runner
    steps:
    - name: Test
      run: |
        if [ -f test_image.sh ]; then ./test_image.sh; fi
